class carsList {
  late List<dynamic> pics;
  late List<dynamic> color;
  late List<dynamic> rents;
  late String name,
      id,
      passenger_capacity,
      controller,
      batteries,
      motor,
      charger,
      charger_time,
      range,
      max_speed,
      windshield,
      turning_radius,
      climbing_capacity,
      view_mirrors,
      lights,
      speedometer,
      multimedia_system,
      step_board,
      rear_armrest,
      seats,
      dashboard,
      side_icebox,
      golf_cart_cover,
      warranty_details,
      driving_system,
      lwh,
      suspension,
      gross_weight,
      payload,
      bumpers,
      tire,
      rim,
      braking_system,
      category,
      price,
      leadacid,
      type;

  carsList(
      {required this.id,
      required this.pics,
      required this.name,
      required this.rents,
      required this.color,
      required this.passenger_capacity,
      required this.controller,
      required this.batteries,
      required this.motor,
      required this.charger,
      required this.charger_time,
      required this.range,
      required this.max_speed,
      required this.windshield,
      required this.turning_radius,
      required this.climbing_capacity,
      required this.view_mirrors,
      required this.lights,
      required this.speedometer,
      required this.multimedia_system,
      required this.step_board,
      required this.rear_armrest,
      required this.seats,
      required this.dashboard,
      required this.side_icebox,
      required this.golf_cart_cover,
      required this.warranty_details,
      required this.driving_system,
      required this.lwh,
      required this.suspension,
      required this.gross_weight,
      required this.payload,
      required this.bumpers,
      required this.tire,
      required this.rim,
      required this.braking_system,
      required this.category,
      required this.price,
      required this.leadacid,
      required this.type});
}
